// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnjmimjlnuwmbsmzgxuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuam1pbWpsbnV3bWJzbXpneHVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4NTAxNjEsImV4cCI6MjA1MjQyNjE2MX0.mxIzHCi1MgR89js5ds5PpAv3Jg8KSvKDBUR5UcDF8aQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);